### ISSUE TITLE
webisoget 2.8.4 won't compile with openssl >= 1.1.0

### ISSUE THREAD

**Issue by ejstacey** [UWIT-IAM/webisoget#6]
When using openssl 1.1.0 and above, webisoget (2.8.4) won't compile.

Two issues come up:
```

webisogetlib.c: In function _sslverify_callback_:
webisogetlib.c:194:7: warning: _ASN1_STRING_data_ is deprecated [-Wdeprecated-declarations]
       altn = (char *)ASN1_STRING_data(ck->d.ia5);
       ^~~~
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from webisogetlib.c:33:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^

```

This is fixed by using the newer ASN1_string_get0_data.  I stole the idea from the eggdrop repo, which had a similar ticket.  They did a proper fix though, determining which openssl version you're running and using the appropriate line.  The pull-request for the fix for them is here: https://github.com/eggheads/eggdrop/pull/373/files

```
In file included from webisogetlib.c:36:0:
webisogetlib.c:205:40: error: _SSL_R_PEER_ERROR_CERTIFICATE_ undeclared (first use in this function)
    SSLerr(SSL_F_SSL_VERIFY_CERT_CHAIN, SSL_R_PEER_ERROR_CERTIFICATE);
                                        ^
```
I don't know where SSL_R_PEER_ERROR_CERTIFICATE comes from or what replaces it in openssl 1.1, so I just commented out throwing the SSL error and compilation succeeded.

**Comment by jimfox** [comment]
Fixed in version 2.8.7
